//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevicesOrder()
        {
            this.DevicesOrderProduct = new HashSet<DevicesOrderProduct>();
        }
    
        public int Id { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> DevicesId { get; set; }
    
        public virtual Devices Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevicesOrderProduct> DevicesOrderProduct { get; set; }
    }
}
